version() {
    local scrname="Gentoo genkernel Compilation Helper"
    local scrver="0.17"
    local scrauth="Marcus Hoffren"
    local authnick="dMG/Up Rough^Divine Stylers^TrueSchool"
    local scrcontact="marcus@harikazen.com"
    echo "${scrname} v${scrver}"
    echo "Copyright (C) 2017 ${scrauth} <${authnick}>."
    echo "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>."
    echo "This is free software: you are free to change and redistribute it."
    echo "There is NO WARRANTY, to the extent permitted by law."
    echo ""
    echo "Written by ${scrauth}. <${scrcontact}>"
    echo ""
}
